CREATE DATABASE homemaking
CHARACTER SET 'utf8'
COLLATE 'utf8_general_ci';
USE homemaking;
CREATE TABLE USER (
	ID			INT AUTO_INCREMENT PRIMARY KEY,
	USERNAME	TEXT,
	PASSWORD	TEXT,
	POWER		INT,
	MONEY		INT,
	IMG			TEXT
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE GOODS (
	ID			INT AUTO_INCREMENT PRIMARY KEY,
	NAME		TEXT,
	PRICE		DOUBLE,
	DES			TEXT,
	ISSELL		INT,
	IMG			TEXT
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE GOODSORDER (
	ID			INT AUTO_INCREMENT PRIMARY KEY,
	ORDERTYPE	TEXT,
	PRICE		DOUBLE,
	SUM			INT,
	GOODS		INT,
	STATE		INT
)ENGINE=InnoDB DEFAULT CHARSET=utf8;