CREATE DATABASE homemaking
CHARACTER SET 'utf8'
COLLATE 'utf8_general_ci';
USE homemaking;
CREATE TABLE USER (
	ID			INT AUTO_INCREMENT PRIMARY KEY,
	USERNAME	TEXT,
	PASSWORD	TEXT,
	POWER		INT,
	MONEY		INT,
	IMG			TEXT,
	PAYPASSWORD	TEXT
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE GOODS (
	ID			INT AUTO_INCREMENT PRIMARY KEY,
	NAME		TEXT,
	PRICE		DOUBLE,
	DES			TEXT,
	ISSELL		INT,
	GOODSTYPE	TEXT,
	ADDRESS		TEXT,
	SEX			TEXT,
	AGE			INT,
	TEL 		TEXT,
	IMG			TEXT
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE GOODSORDER (
	ID			INT AUTO_INCREMENT PRIMARY KEY,
	ORDERTYPE	TEXT,
	PRICE		DOUBLE,
	SUM			INT,
	GOODS		INT,
	UID			INT,
	STATE		INT,
	TPRICE		DOUBLE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE AD (
	ID			INT AUTO_INCREMENT PRIMARY KEY,
	IMG			TEXT,
	URL			TEXT,
	GOODSID		INT,
	MSG			TEXT
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE NOTICE (
	ID			INT AUTO_INCREMENT PRIMARY KEY,
	TITLE		TEXT,
	NDESCRIBE	TEXT, 
	TYPE		TEXT,
	NTIME		TEXT,
	URL			TEXT
)ENGINE=InnoDB DEFAULT CHARSET=utf8;